server:
  port: 8081

logging:
  level:
    root: INFO
    com.joe.restAPIs : DEBUG
  file: logs.log

spring:
  profiles:
    active: QA



---
spring:
  config:
    activate:
      on-profile: QA
  datasource:
    url: jdbc:postgresql://localhost:5432/departmentsdbqa
    username: postgres
    password: Bingo

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
initial:
  message: Welcome to REST API using spring boot

management:
  endpoints:
    web:
      exposure:
        include: "features, info, health"

---
spring:
  config:
    activate:
      on-profile: TEST
  datasource:
    url: jdbc:h2:/home/joe/test;DB_CLOSE_ON_EXIT=FALSE # JDBC URL for an in-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
     enabled: true # Enable the H2 Console for web-based database management
     tcpServer:
  enabled: true # Enable the H2 TCP server for remote database access
initial:
  message : Welcome to REST API using spring boot

---

spring:
  config:
    activate:
      on-profile: PROD
  datasource:
    url: ${DB_URLPROD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
initial:
  message: Welcome to REST API using spring boot